# Generated by Django 4.2.1 on 2023-08-18 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('zip_code', models.SmallIntegerField()),
                ('banner_picture', models.ImageField(upload_to='service_providers_banners')),
                ('mobile', models.CharField(max_length=50)),
                ('expired_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prices', models.TextField(blank=True, null=True)),
                ('booking_date_nr', models.SmallIntegerField(default=7)),
                ('booking_time_interval', models.SmallIntegerField(default=30)),
                ('type', models.CharField(choices=[('saloon', 'Fordrászat'), ('nails', 'Műkörmös'), ('solarium', 'Szolárium')], max_length=15)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_providers_pictures')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.serviceprovider')),
            ],
        ),
    ]
