# Generated by Django 5.1 on 2024-08-22 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('zip_code', models.SmallIntegerField()),
                ('banner_picture', models.ImageField(upload_to='service_providers_banners')),
                ('mobile', models.CharField(max_length=50)),
                ('expired_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('prices', models.TextField(blank=True, null=True)),
                ('booking_date_nr', models.SmallIntegerField(default=7)),
                ('booking_time_interval', models.SmallIntegerField(default=30)),
                ('type', models.CharField(choices=[('salon', 'Fodrászat'), ('nails', 'Műkörmös'), ('solarium', 'Szolárium'), ('kozmetikus', 'Kozmetikus')], default=('salon', 'Fodrászat'), max_length=15)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Hétfő'), ('2', 'Kedd'), ('3', 'Szerda'), ('4', 'Csütörtök'), ('5', 'Péntek'), ('6', 'Szombat'), ('7', 'Vasárnap')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='service_provider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_providers_pictures')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refer_pictures', to='service_provider.serviceprovider')),
            ],
        ),
    ]
