# Generated by Django 4.2.1 on 2023-08-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='type',
            field=models.CharField(choices=[('salon', 'Fordrászat'), ('nails', 'Műkörmös'), ('solarium', 'Szolárium')], default=('salon', 'Fordrászat'), max_length=15),
        ),
    ]
