# Generated by Django 4.2.1 on 2023-08-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_alter_serviceprovider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='type',
            field=models.CharField(choices=[('salon', 'Fodrászat'), ('nails', 'Műkörmös'), ('solarium', 'Szolárium')], default=('salon', 'Fodrászat'), max_length=15),
        ),
    ]
