# Generated by Django 4.2.1 on 2023-08-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_serviceprovider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
