# Generated by Django 4.2.1 on 2023-08-22 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0006_alter_serviceprovider_expired_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderOpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Hétfő'), ('2', 'Kedd'), ('3', 'Szerda'), ('4', 'Csütörtök'), ('5', 'Péntek'), ('6', 'Szombat'), ('7', 'Vasárnap')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.serviceprovider')),
            ],
        ),
    ]
