# Generated by Django 4.2.1 on 2023-08-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0007_serviceprovideropeninghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovideropeninghours',
            name='day',
            field=models.CharField(choices=[('1', 'Hétfő'), ('2', 'Kedd'), ('3', 'Szerda'), ('4', 'Csütörtök'), ('5', 'Péntek'), ('6', 'Szombat'), ('0', 'Vasárnap')], max_length=1),
        ),
        migrations.AlterField(
            model_name='serviceprovideropeninghours',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='service_provider.serviceprovider'),
        ),
    ]
