# Generated by Django 4.2.1 on 2023-08-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0008_alter_serviceprovideropeninghours_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovideropeninghours',
            name='day',
            field=models.CharField(choices=[('1', 'Hétfő'), ('2', 'Kedd'), ('3', 'Szerda'), ('4', 'Csütörtök'), ('5', 'Péntek'), ('6', 'Szombat'), ('7', 'Vasárnap')], max_length=1),
        ),
    ]
