# Generated by Django 4.2.1 on 2023-09-05 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0009_alter_serviceprovideropeninghours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderpicture',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refer_pictures', to='service_provider.serviceprovider'),
        ),
    ]
