# Generated by Django 5.1 on 2024-08-22 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('rate', models.SmallIntegerField(choices=[(1, 'Nem ajánlom'), (2, 'Tűrhető'), (3, 'Átlagos'), (4, 'Jó'), (5, 'Kiválló')])),
                ('description', models.TextField(blank=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_ratings', to='service_provider.serviceprovider')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_ratings', to='account.userprofile')),
            ],
        ),
    ]
