# Generated by Django 4.2.1 on 2023-09-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.SmallIntegerField(choices=[(1, 'Nem ajánlom'), (2, 'Tűrhető'), (3, 'Átlagos'), (4, 'Jó'), (5, 'Kiválló')]),
        ),
    ]
