# Generated by Django 5.1 on 2024-08-22 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('accept_description', models.TextField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bookings', to='account.userprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='service_provider.serviceprovider')),
            ],
        ),
    ]
