# Generated by Django 4.2.1 on 2023-08-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
