# Generated by Django 4.2.1 on 2023-08-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('service_provider', '0006_alter_serviceprovider_expired_date'),
        ('booking', '0004_alter_booking_booked_user_alter_booking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bookings', to='account.userprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='service_provider.serviceprovider'),
        ),
    ]
