# Generated by Django 4.2.1 on 2023-08-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_booked_user_alter_booking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rating',
        ),
    ]
